hotlibrary/urls.py
from django.urls import include, path


from hotlibrary.views import APIviews, students
from hotlibrary.views.APIviews import LecturerResourceUploadCompleteHandler
from hotlibrary.views.indexviews import AboutView, AndroidView, verify_user_upload, staff_signup_view
from hotlibrary.views.students import student_signup_view
from .views import admins, lecturers, librarians, indexviews

urlpatterns = [
    path('about/', AboutView.as_view(), name='about'),
    path('android/', AndroidView.as_view(), name='android'),
    path('verify/', verify_user_upload, name='verify',),
    path('staffs/accounts/signup/', staff_signup_view, name='staffsignup'),

    path('admins/', include(([
        path('uploads/', indexviews.VerifyUploadView.as_view(), name='uploads'),
        path('uploads/tutorials/', admins.TutorialUploadView.as_view(), name='tutorials'),
        path('uploads/resources/', admins.ResourceUploadView.as_view(), name='resources'),
        path('uploads/challenges/', admins.ChallengeUploadView.as_view(), name='challenges'),
        path('uploads/howto/', admins.HowUploadView.as_view(), name='howtos'),
    ], 'hotlibrary'), namespace='admins')),

    path('lecturers/', include(([
        path('lectureruploads/', lecturers.LecturerUploadView.as_view(), name='lectureruploads'),
        path('test/', lecturers.UploadTest.as_view(), name='upload-home'),
        path('api/files/policy/', APIviews.LecturerUploadAPI.as_view(), name='upload-policy'),
        path('api/files/complete/', LecturerResourceUploadCompleteHandler.as_view(), name='upload-complete'),
    ], 'hotlibrary'), namespace='lecturers')),

    path('librarian/', include(([
        path('librarianuploads/', librarians.LibrarianUploadView.as_view(), name='librarianuploads'),
        path('api/files/policy/', APIviews.LibrarianUploadAPI.as_view(), name='upload-policy'),
    ], 'hotlibrary'), namespace='librarians')),

    path('students/', include(([
        path('downloads/', students.StudentView.as_view(), name='download'),
        path('accounts/signup/', student_signup_view, name='stdsignup'),
    ], 'hotlibrary'), namespace='students')),



]

hotlibrary/views/APIviews.py
import base64
import hashlib
import hmac
import os
import time
from rest_framework import permissions, status, authentication
from rest_framework.response import Response
from rest_framework.views import APIView
from hotlibrary.serializers import LecturerResourceSerializer, LibrarianResourceSerializer
from hotlibrary.config_aws import (
    AWS_UPLOAD_BUCKET,
    AWS_UPLOAD_REGION,
    AWS_UPLOAD_ACCESS_KEY_ID,
    AWS_UPLOAD_SECRET_KEY
)
from hotlibrary.models import (LecturerResource, LibrarianResource,
                               AdminTutorial, AdminResource, AdminChallenge, AdminHowToRepo, FileItem)


class LecturerUploadAPI(APIView):
    permission_classes = [permissions.IsAuthenticated]
    authentication_classes = [authentication.SessionAuthentication]

    def post(self, request, *args, **kwargs):
        # course = request.data.get('course')
        # unit_code = request.data.get('unit_code')
        # semester = request.data.get('semester')
        # resource_type = request.data.get('resource_type')
        filename_req = request.data.get('filename')
        if not filename_req:
            return Response({"message": "A filename is required"}, status=status.HTTP_400_BAD_REQUEST)
        policy_expires = int(time.time() + 5000)
        user = request.user
        username_str = str(request.user.username)

        file_obj = FileItem.objects.create(user=user, name=filename_req)
        file_obj_id = file_obj.id
        upload_start_path = "LecturerResources/{username}/{file_obj_id}/".format(
            username=username_str,
            file_obj_id=file_obj_id
        )
        _, file_extension = os.path.splitext(filename_req)
        filename_final = "{file_obj_id}{file_extension}".format(
            file_obj_id=file_obj_id,
            file_extension=file_extension

        )
        final_upload_path = "{upload_start_path}{filename_final}".format(
            upload_start_path=upload_start_path,
            filename_final=filename_final,
        )
        if filename_req and file_extension:
            file_obj.path = final_upload_path
            file_obj.save()

        policy_document_context = {
            "expire": policy_expires,
            "bucket_name": AWS_UPLOAD_BUCKET,
            "key_name": "",
            "acl_name": "private",
            "content_name": "",
            "content_length": 524288000,
            "upload_start_path": upload_start_path,

        }
        policy_document = """
        {"expiration": "2019-01-01T00:00:00Z",
          "conditions": [ 
            {"bucket": "%(bucket_name)s"}, 
            ["starts-with", "$key", "%(upload_start_path)s"],
            {"acl": "%(acl_name)s"},

            ["starts-with", "$Content-Type", "%(content_name)s"],
            ["starts-with", "$filename", ""],
            ["content-length-range", 0, %(content_length)d]
          ]
        }
        """ % policy_document_context
        aws_secret = str.encode(AWS_UPLOAD_SECRET_KEY)
        policy_document_str_encoded = str.encode(policy_document.replace(" ", ""))
        url = 'https://{bucket}.s3-{region}.amazonaws.com/'.format(
            bucket=AWS_UPLOAD_BUCKET,
            region=AWS_UPLOAD_REGION
        )
        policy = base64.b64encode(policy_document_str_encoded)
        signature = base64.b64encode(hmac.new(aws_secret, policy, hashlib.sha1).digest())
        data = {
            "policy": policy,
            "signature": signature,
            "key": AWS_UPLOAD_ACCESS_KEY_ID,
            "file_bucket_path": upload_start_path,
            "file_id": file_obj_id,
            "filename": filename_final,
            "url": url,
            "username": username_str,
            # "course": course,
            # "unit_code": unit_code,
            # "semester": semester,
            # "resource_type": resource_type
        }
        return Response(data, status=status.HTTP_200_OK)


class LecturerResourceUploadCompleteHandler(APIView):
    permission_classes = [permissions.IsAuthenticated]
    authentication_classes = [authentication.SessionAuthentication]

    def post(self, request, *args, **kwargs):
        file_id = request.POST.get('file')
        size = request.POST.get('fileSize')
        data = {}
        type_ = request.POST.get('fileType')
        if file_id:
            obj = LecturerResource.objects.get(id=int(file_id))
            obj.size = int(size)
            obj.uploaded = True
            obj.type = type_
            obj.save()
            data['id'] = obj.id
            data['saved'] = True
        return Response(data, status=status.HTTP_200_OK)


class LibrarianUploadAPI(APIView):
    permission_classes = [permissions.IsAuthenticated]
    authentication_classes = [authentication.SessionAuthentication]

    def post(self, request, *args, **kwargs):
        course_name = request.data.get('course_name')
        academic_year = request.data.get('academic_year')
        filename_req = request.data.get('filename')
        if not filename_req:
            return Response({"message": "A filename is required"}, status=status.HTTP_400_BAD_REQUEST)
        policy_expires = int(time.time() + 5000)
        user = request.user
        username_str = str(request.user.username)

        file_obj = LibrarianResource.objects.create(user=user, name=filename_req,
                                                    academic_year=academic_year, course_name=course_name)
        file_obj_id = file_obj.id
        upload_start_path = "LibrarianResources/{username}/{file_obj_id}/".format(
            username=username_str,
            file_obj_id=file_obj_id
        )
        _, file_extension = os.path.splitext(filename_req)
        filename_final = "{file_obj_id}{file_extension}".format(
            file_obj_id=file_obj_id,
            file_extension=file_extension

        )

        final_upload_path = "{upload_start_path}{filename_final}".format(
            upload_start_path=upload_start_path,
            filename_final=filename_final,
        )
        if filename_req and file_extension:
            file_obj.path = final_upload_path
            file_obj.save()

        policy_document_context = {
            "expire": policy_expires,
            "bucket_name": AWS_UPLOAD_BUCKET,
            "key_name": "",
            "acl_name": "private",
            "content_name": "",
            "content_length": 524288000,
            "upload_start_path": upload_start_path,

        }
        policy_document = """
        {"expiration": "2019-01-01T00:00:00Z",
          "conditions": [ 
            {"bucket": "%(bucket_name)s"}, 
            ["starts-with", "$key", "%(upload_start_path)s"],
            {"acl": "%(acl_name)s"},

            ["starts-with", "$Content-Type", "%(content_name)s"],
            ["starts-with", "$filename", ""],
            ["content-length-range", 0, %(content_length)d]
          ]
        }
        """ % policy_document_context
        aws_secret = str.encode(AWS_UPLOAD_SECRET_KEY)
        policy_document_str_encoded = str.encode(policy_document.replace(" ", ""))
        url = 'https://{bucket}.s3-{region}.amazonaws.com/'.format(
            bucket=AWS_UPLOAD_BUCKET,
            region=AWS_UPLOAD_REGION
        )
        policy = base64.b64encode(policy_document_str_encoded)
        signature = base64.b64encode(hmac.new(aws_secret, policy, hashlib.sha1).digest())
        data = {
            "policy": policy,
            "signature": signature,
            "key": AWS_UPLOAD_ACCESS_KEY_ID,
            "file_bucket_path": upload_start_path,
            "file_id": file_obj_id,
            "filename": filename_final,
            "url": url,
            "username": username_str,
            "course_name": course_name,
            "academic_year": academic_year
        }
        return Response(data, status=status.HTTP_200_OK)


class LibrarianResourceUploadCompleteHandler(APIView):
    permission_classes = [permissions.IsAuthenticated]
    authentication_classes = [authentication.SessionAuthentication]

    def post(self, request, *args, **kwargs):
        file_id = request.POST.get('file')
        size = request.POST.get('fileSize')
        data = {}
        type_ = request.POST.get('fileType')
        if file_id:
            obj = LibrarianResource.objects.get(id=int(file_id))
            obj.size = int(size)
            obj.uploaded = True
            obj.type = type_
            obj.save()
            data['id'] = obj.id
            data['saved'] = True
        return Response(data, status=status.HTTP_200_OK)


class AdminResourceUploadAPI(APIView):
    permission_classes = [permissions.IsAuthenticated]
    authentication_classes = [authentication.SessionAuthentication]

    def post(self, request, *args, **kwargs):
        resource_type = request.data.get('resource_type')
        resource_name = request.data.get('resource_name')
        resource_description = request.data.get('resource_description')
        filename_req = request.data.get('filename')
        if not filename_req:
            return Response({"message": "A filename is required"},
                            status=status.HTTP_400_BAD_REQUEST)
        policy_expires = int(time.time() + 5000)
        user = request.user
        username_str = str(request.user.username)
        file_obj = AdminResource.objects.create(user=user, name=filename_req,
                                                resource_type=resource_type,
                                                resource_name=resource_name,
                                                resource_description=resource_description)
        file_obj_id = file_obj.id
        upload_start_path = "AdminResources/{username}/{file_obj_id}/".format(
            username=username_str,
            file_obj_id=file_obj_id
        )
        _, file_extension = os.path.splitext(filename_req)
        filename_final = "{file_obj_id}{file_extension}".format(
            file_obj_id=file_obj_id,
            file_extension=file_extension

hotlibrary/views/admins.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.utils.decorators import method_decorator
from django.views.generic import CreateView

from ..decorators import admin_required
from ..models import AdminChallenge, AdminResource, AdminTutorial, AdminHowToRepo


@method_decorator([login_required, admin_required], name='dispatch')
class TutorialUploadView(CreateView):
    model = AdminTutorial
    fields = ('tutorial_type', 'tutorial_name', 'tutorial_description')
    template_name = 'hotlibrary/admins/tutorialupload.html'

    def form_valid(self, form):
        admintutorial = form.save(commit=False)
        admintutorial.owner = self.request.user
        admintutorial.save()
        messages.success(self.request, 'The Tutorial(s) were upload successfully')
        return redirect('admins:uploads')


@method_decorator([login_required, admin_required], name='dispatch')
class ResourceUploadView(CreateView):
    model = AdminResource
    fields = ('resource_type', 'resource_name', 'resource_description')
    template_name = 'hotlibrary/admins/resourceupload.html'

    def form_valid(self, form):
        adminresource = form.save(commit=False)
        adminresource.owner = self.request.user
        adminresource.save()
        messages.success(self.request, 'The Resource(s) were upload successfully')
        return redirect('admins:uploads')


@method_decorator([login_required, admin_required], name='dispatch')
class ChallengeUploadView(CreateView):
    model = AdminChallenge
    fields = ('challenge_category', 'challenge_name', 'challenge_level', 'challenge_description')
    template_name = 'hotlibrary/admins/challengeupload.html'

    def form_valid(self, form):
        adminchallenge = form.save(commit=False)
        adminchallenge.owner = self.request.user
        adminchallenge.save()
        messages.success(self.request, 'The Challenge(s) were upload successfully')
        return redirect('admins:uploads')


@method_decorator([login_required, admin_required], name='dispatch')
class HowUploadView(CreateView):
    model = AdminHowToRepo
    fields = ('howto_description',)
    template_name = 'hotlibrary/admins/howtoupload.html'

    def form_valid(self, form):
        adminhowto = form.save(commit=False)
        adminhowto.owner = self.request.user
        adminhowto.save()
        messages.success(self.request, 'The How Packs were upload successfully')
        return redirect('admins:uploads')

hotlibrary/views/indexviews.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView

from hotlibrary.decorators import admin_required, superuser_required
from hotlibrary.forms import StaffSignupForm


def verify_user_upload(request):
    if request.user.is_authenticated:
        if request.user.is_admin:
            return redirect('admins:uploads')
        elif request.user.is_lecturer:
            return redirect('lecturers:lectureruploads')
        elif request.user.is_librarian:
            return redirect('librarians:librarianuploads')
        else:
            return render(request, 'hotlibrary/whoops.html')
    else:
        return render(request, 'hotlibrary/whoopy.html')


# you do not have permissions to view this page, Contact the administrator for approval


class HomeView(TemplateView):
    template_name = 'hotlibrary/index.html'


class AboutView(TemplateView):
    template_name = 'hotlibrary/about.html'


@method_decorator([login_required, admin_required], name='dispatch')
class VerifyUploadView(TemplateView):
    template_name = 'hotlibrary/upload.html'


class AndroidView(TemplateView):
    template_name = 'android.html'


@superuser_required(login_url='login')
def staff_signup_view(request):
    if request.method == 'POST':
        form = StaffSignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('staffsignup')
    else:
        form = StaffSignupForm()
    return render(request, 'accounts/staff_signup.html', {'form': form})

hotlibrary/views/lecturers.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, TemplateView

from ..decorators import lecturer_required
from ..models import LecturerResource


@method_decorator([login_required, lecturer_required], name='dispatch')
class LecturerUploadView(CreateView):
    model = LecturerResource
    fields = ('course', 'unit_code', 'semester', 'resource_type')
    template_name = 'hotlibrary/lecturers/lecturerupload.html'

    def form_valid(self, form):
        lecturerresource = form.save(commit=False)
        lecturerresource.owner = self.request.user
        lecturerresource.save()
        messages.success(self.request, 'The Resources(s) were upload successfully')
        return redirect('home')


class UploadTest(TemplateView):
    template_name = 'hotlibrary/lecturers/apitest.html'

hotlibrary/templates/hotlibrary/about.html
<!-- About us section -->
{%extends 'base.html'%}
{% block content %}
{% load static %}
<div class="containers padding">
	<section class="header1 cid-qyvisAZ1Bw" id="About" data-rv-view="758">
  <div class="container-fluid padding">
    <div class="row justify-content-md-center">
      <div class="mbr-white col-md-10">
        <h1 class="mbr-section-title align-center mbr-bold pb-3 mbr-fonts-style display-5">"Alone we can do so little, together we can do so much." --Helen Keller</h1>
        <h3 class="mbr-section-subtitle align-center mbr-light pb-3 mbr-fonts-style display-4">MEET OUR TEAM</h3>
        <p class="mbr-text align-center pb-3 mbr-fonts-style display-5">
          We are all very different. We were born in different cities, at different times, we love different music,
          food, movies. But we have something that unites us all. It is the ability to identify a Problem and Solve it. We are a company. We are its heart.
          We are not just a team, we are a family.
        </p>
        </div>
      </div>
    </div>
    <div class="container-fluid padding">
      <div class="row padding">
        <div class="col-md-4">
          <div class="card border-info">
          <div class="user_image">
              <img src='{% static "img/team1.png" %}' alt="Emmanuel" title="" media-simple="true">
          </div>
            <div class="card-body">
              <h4 class="card-title">Emmanuel Atemba</h4>
              <p class="card-text">Emmanuel is a third Year Student</p>
              <!-- <a href="#" class="btn btn-outline-secondary">See Profile</a> -->
            </div>
          </div>
        </div>

        <div class="col-md-4">
          <div class="card border-info">
          <div class="user_image">
              <img src='{% static "img/team2.png" %}' alt="Grace" title="" media-simple="true">
          </div>
            <div class="card-body">
              <h4 class="card-title">Grace Mbira</h4>
              <p class="card-text">Grace is a third Year Student</p>
              <!-- <a href="#" class="btn btn-outline-secondary">See Profile</a> -->
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card border-info">
          <div class="user_image">
              <img src='{% static "img/team3.png" %}' alt="John" title="" media-simple="true">
          </div>
            <div class="card-body">
              <h4 class="card-title">John Kamau</h4>
              <p class="card-text">John is a third Year Student</p>
              <!-- <a href="#" class="btn btn-outline-secondary">See Profile</a> -->
            </div>
          </div>
        </div>
      </div>
    </div>
      <br>
    <h1 class="mbr-section-title align-center mbr-bold pb-3 mbr-fonts-style display-5" id="connect" >We are change makers, Filling gaps in education sector through Technology.</h1>
</section>
</div>

	{% block footer %}
	{% include 'snippets/footer.html' %}
	{% endblock %}
{% endblock %}

hotlibrary/templates/hotlibrary/index.html
{%extends 'base.html'%}

{% block content %}
<style>
    .containers{
    background-color: #A3D8F1;
    padding-top: 50px;
    padding-left: 50px;
    padding-right: 50px;
    padding-bottom:0px
    margin-bottom: 0px;
    }
    .card{
    background-color: #A3D8F1;

    border: #A3D8F1

}
</style>
{% load static %}
  <div class="container-fluids">
    <div class="center-page-content-wrapper"><div class="offscreen-overflow-custom-spacing-wrapper">
      <div class="_1145-content-wrapper">
        <div data-w-id="bf4cece6-6c5f-aeb9-8ac9-a7fc7466d258" class="large-offscreen-graphic-row graphic-right">
          <div class="flex-text-left _430 _100-percent">
            <div class="spacing-wrapper-xxlarge">
              <h2 data-ix="new-hw-an-see-hw-play" class="proxima-a">
                Experience the Finest way of sharing resources</h2>
              </div>
              <div class="spacing-wrapper-medium">
                <h4>Reliable and Multi-purpose than any other Learning Application</h4>
              </div><div class="home-combined-chart-right mobile">
                <img src='{% static "img/onetwo.svg" %}' data-ix="hw-an-play-video-show-modal" alt="" class="home-combined-chart-offscreen">
              </div>
              <div class="spacing-wrapper-large">
                <p>
                  Sharing lecture notes and resources using WhatsApp is a huge pain. You need
                  to scroll through unnecessary messages to get to the document. The file size
                  limit is annoying. On the othe hands, Flash disks are prone malicious programs,
                  this aint cool. With HotLib Application you will Experience awesoness like no other,
                  all the resources are uploaded to the server and fetched by students using Maseno HotLib App
                  installed on their devices; Its Ease, Convinient and Multi-purpose.
                </p>
              </div>
              <div class="spacing-wrapper">
                <a href="#"
                class="btn btn-primary-outline display-4">
                Fast and Free. Get Started</a>
              </div>
            </div>
            <div class="home-combined-chart-right">
              <img src='{% static "img/onetwo.svg" %}' data-ix="hw-an-play-video-show-modal" alt="" class="home-combined-chart-offscreen">
              <div class="homw-hw-combined-background"><div class="home-combined-charts-backgrounds">
              </div>
              <div class="home-combined-charts-backgrounds green">
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="containers padding" id="cards">
  <div class="row">
    <div class="col-sm-12 col-md-4 col-lg-4">
      <div class="card " >
        <div class="card-header text-success text-center" style="font-size: 18px; font-family: 'Aclonica';">Lecture Notes</div>
        <div class="card-body" style="font-size: 16px;text-align:justify">
          Are you a Lecturer in Maseno University? Are you stranded on which platform
          to use to send notes and assignments to your students?
          Look no more..Introducing Maseno HotLib Application, which allows Lecturers to upload notes, assignments and CATS
          for students to access and download using their <a href="/android/">Maseno HotLib android application.</a>
          Its Reliable and Convinient.

        </div>

      </div>
    </div>
    <div class="col-sm-12 col-md-4 col-lg-4">
      <div class="card ">
        <div class="card-header text-success text-center" style="font-size: 18px; font-family: 'Aclonica';">Past Papers</div>
        <div class="card-body" style="font-size: 16px; text-align:justify" >
          Are you a Librarian having hard time dealing with congestions in the library.
          We've have brough great things to you. We've made your work easier that it seems,
          Upload pastpapers through this web Application, for students to access and download
          them using their android application. No more congestions,<br>
          Its Easy and Fast.
        </div>

      </div>
    </div>
    <div class="col-sm-12 col-md-4 col-lg-4">
      <div class="card ">
        <div class="card-header text-success text-center" style="font-size: 18px; font-family: 'Aclonica';">More Features</div>
        <div class="card-body" style="font-size: 16px; text-align:justify">
          Experience inifinity of learning resources from videos,
          PDfs, links and How to find features in the HotLib android Application.
          Exclusively solve challenges and track your journey from beginner level to expert level
          in any programming language of your choice. Ask and Answer questions in the Academic Forum
          and Learn more everyday. Help and Learn from others paradigm.

        </div>

      </div>
    </div>

  </div>
    {% include 'snippets/footer.html' %}

</div>

{% endblock %}

hotlibrary/templates/hotlibrary/upload.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <br><br>
    <div class="row text-center">
        <div class="col-12 justify-text-center">
        <h2>Welcome to the Maseno HotLibrary Admin Upload Section <span class="icon-emo-happy"></span></h2>
  <p class="lead text-center">
      You are required to select a category to upload the resources of your choosing. Please make sure you upload the
      right content at the right location.
      <br><br>
  </p>
        </div>
        <div class="col-3">
            <a href="{% url 'admins:tutorials' %}" class="btn btn-success btn-lg" role="button">Tutorial Upload</a>
        </div>
          <div class="col-3">
             <a href="{% url 'admins:resources' %}" class="btn btn-warning btn-lg" role="button">Resource Upload</a>
        </div>
          <div class="col-3">
              <a href="{% url 'admins:challenges' %}" class="btn btn-primary btn-lg" role="button">Challenges Upload</a>
        </div>
         <div class="col-3">
            <a href="{% url 'admins:howtos' %}" class="btn btn-info btn-lg" role="button">How To Pack</a>
        </div>
    </div>

</div>

  <hr>
<p>Thank you.</p>

{% endblock %}

hotlibrary/templates/hotlibrary/whoops.html
{% extends 'base.html' %}

{% block content %}
<div class="container " style="width: 55rem;">
    <div class="row text-center">
        <div class="col-sm-12 col-md-12 col-lg-12">
                     <h2 class="text-danger">If you are viewing this page, it means that you do not have enough permissions to access this page.</h2>
  <p class="lead">Please login with an account that has uploading privileges!!</p><br>
             </div>
        <div class="col-sm-12 col-md-12 col-lg-12">

      <div class="text-center">
         <a href="{% url 'login' %}" class="btn btn-primary btn-sm" role="button">Proceed to Login</a>
    </div>
        </div>

    </div>

</div>

  </div>




{% endblock %}

hotlibrary/templates/hotlibrary/whoopy.html
{% extends 'base.html' %}

{% block content %}
<div class="container " style="width: 55rem;">
    <div class="row text-center">
        <div class="col-sm-12 col-md-12 col-lg-12">
                     <h2 class="text-danger">If you are viewing this page, it means that you are  not authenticated.</h2>
  <p class="lead">Please login to gain access.</p><br>
             </div>
        <div class="col-sm-12 col-md-12 col-lg-12">

      <div class="text-center">
         <a href="{% url 'login' %}" class="btn btn-primary btn-sm" role="button">Proceed to Login</a>
    </div>
        </div>

    </div>

</div>

  </div>




{% endblock %}