hotlibrary/urls.py
from django.urls import include, path


from hotlibrary.views import APIviews, students
from hotlibrary.views.APIviews import LecturerResourceUploadCompleteHandler
from hotlibrary.views.indexviews import AboutView, AndroidView, verify_user_upload, staff_signup_view
from hotlibrary.views.students import student_signup_view
from .views import admins, lecturers, librarians, indexviews

urlpatterns = [
    path('about/', AboutView.as_view(), name='about'),
    path('android/', AndroidView.as_view(), name='android'),
    path('verify/', verify_user_upload, name='verify',),
    path('staffs/accounts/signup/', staff_signup_view, name='staffsignup'),

    path('admins/', include(([
        path('uploads/', indexviews.VerifyUploadView.as_view(), name='uploads'),
        path('uploads/tutorials/', admins.TutorialUploadView.as_view(), name='tutorials'),
        path('uploads/resources/', admins.ResourceUploadView.as_view(), name='resources'),
        path('uploads/challenges/', admins.ChallengeUploadView.as_view(), name='challenges'),
        path('uploads/howto/', admins.HowUploadView.as_view(), name='howtos'),
    ], 'hotlibrary'), namespace='admins')),

    path('lecturers/', include(([
        path('lectureruploads/', lecturers.LecturerUploadView.as_view(), name='lectureruploads'),
        path('test/', lecturers.UploadTest.as_view(), name='upload-home'),
        path('api/files/policy/', APIviews.LecturerUploadAPI.as_view(), name='upload-policy'),
        path('api/files/complete/', LecturerResourceUploadCompleteHandler.as_view(), name='upload-complete'),
    ], 'hotlibrary'), namespace='lecturers')),

    path('librarian/', include(([
        path('librarianuploads/', librarians.LibrarianUploadView.as_view(), name='librarianuploads'),
        path('api/files/policy/', APIviews.LibrarianUploadAPI.as_view(), name='upload-policy'),
    ], 'hotlibrary'), namespace='librarians')),

    path('students/', include(([
        path('downloads/', students.StudentView.as_view(), name='download'),
        path('accounts/signup/', student_signup_view, name='stdsignup'),
    ], 'hotlibrary'), namespace='students')),



]

templates/snippets/footer.html
{% load static %}
<footer class="container-fluid padding">
  <div class="row text-center">
    <div class="col-md-4">
      <img src='{% static "img/hotlibb.png" %}' alt="hotlib icon" height="70" width="70">
    
        <strong> Betahood Apps </strong>
    </div>
    <div class="col-8">
      <hr>
      
       <P>&copy; {% now "Y" %} Betahood Inc.  All Rights Reserved.</P>
    
      <hr>
    </div>
  </div>
</footer>

templates/snippets/navbar.html
{% load static %}
{% block style_code %}
<link rel="stylesheet" href='{% static "android/css/navbar.css" %}'>
 <link rel="stylesheet" href='{% static "android/css/responsive.css" %}'>
 <link rel="stylesheet" href='{% static "android/css/navbarmain.css" %}'>
 <link rel="stylesheet" href='{% static "android/css/line-icons.css" %}'>
	{% endblock style_code %}
    <nav class="navbar navbar-expand-md bg-inverse fixed-top">
        <div class="container-fluid">
          <a class="navbar-brand" href="/"><img src='{% static "img/hotlib.png" %}'></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <i class="lni-menu"></i>
          </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto w-100 justify-content-end">
              <li class="nav-item">
                <a class="nav-link " href="/">HOME</a>
              </li>
              <li class="nav-item">
                <a class="nav-link " href="/about/">ABOUT US</a>
              </li>
              <li class="nav-item">
                <a class="nav-link " href="{% url 'verify' %}">UPLOAD</a>
              </li>
                {% if user.is_authenticated %}
                    {% if user.is_student%}
                <li class="nav-item">
                <a class="nav-link" href="{% url 'students:download' %}">STUDENT</a>
              </li>
                {% endif %}
                 {% endif %}
              <li class="nav-item">
                <a class="nav-link " href="/android/">ANDROID APP</a>
              </li>
                {% if user.is_authenticated %}
                    {% if user.is_superuser%}
                       <li class="nav-item">
                        <a class="nav-link " href="{% url 'staffsignup'%}">REGISTER STAFF</a>
                      </li>
                    {% endif %}
                 {% endif %}
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <div class="text-sucess">
                        <a class="nav-link" href="#" role="button" class="btn popovers" data-toggle="popover" title="You will be logged out!" data-placement="bottom"
                       data-content="Click username to cancel<br><a href='{% url 'logout' %}'>Confirm logout</a>"
                       data-original-title="test title"> User: {{ user.get_username }}</a>
                    </div>
                </li>
                {% else %}
                 <li class="nav-item dropdown">
                    <a class="dropdown-toggle nav-link " href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      ACCOUNT
                    </a>
                     <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="nav-link" href="{% url 'login'%}?next={{request.path}}" > <h4>Login</h4></a>
                        <a class="dropdown-toggle nav-link " href="#" id="subnavbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Register
                        </a>
                     <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                         <a class="nav-link" href="{% url 'students:stdsignup'%}"><h4>I'm Student</h4></a>
                         <a class="nav-link" data-toggle="modal" data-target="#myModal" href="#">I'm Lecturer</a>
                         <a class="nav-link" data-toggle="modal" data-target="#myModal" href="#">I'm Librarian</a>
                      </div>
                    </div>
                </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="false" style=" overflow: scroll; height:auto;">
<div class="modal-dialog">
<div class="modal-content">
  <div class="modal-header">
    <h3 class="modal-title text-danger">Action Could Not Be Completed</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
 <div class="modal-body">
      <div>
          <h4>Staff Registrations can only be done by the system admin.
           <strong>Contact Admin</strong> </h4> <div><a  class="btn btn-info btn-lg btn-block" role="button"
                                                  href="https://mail.google.com/mail/?view=cm&fs=1&tf=1&to=atembaemm07@gmail.com
               &su=REQUEST FOR REGISTRATION AS HOTLIB STAFF" target="_blank" style="color: #ffffff !important;">SEND MAIL</a></div>
      </div>
  </div>
      <div class="modal-footer">
          <div><p>&copy; {% now "Y" %} Betahood Inc.  All Rights Reserved.</p></div>
  </div>
</div>
</div>
</div>